[package]
name = "codize"
version = "0.1.0"
edition = "2021"
description = "A simple library for encoding nested code blocks"
repository = "https://github.com/iTNTPiston/codize"
license = "GPL-3.0"
authors = ["iTNTPiston <terrabyte100k@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
