version: '3'

tasks:
  check:
    desc: Check for issues
    vars:
      CLIPPY_ARGS: -D warnings -D clippy::todo
    cmds:
    - cargo clippy --all-features --all-targets -- {{.CLIPPY_ARGS}}
    - cargo fmt --check

  fix:
    desc: Run formatter
    cmds:
    - cargo fmt

  test:
    desc: Run tests
    cmds:
    - cargo test

  dev:
    desc: Run tests in watch mode
    cmds:
    - cargo watch -x test

  doc:
    desc: Run and serve cargo doc
    cmds:
    - cargo doc
    - task: doc:serve

  doc:serve:
    dir: target/doc
    cmds:
    - python -m http.server 8000
